name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3

      - name: Instalar Dependências
        run: |
          npm install style-dictionary --save
          npm install lru-cache

      - name: Transformar Tokens do Figma
        run: npx token-transformer tokens.json tokens/input.json

      - name: Registrar Transformadores Customizados
        run: node registerTransforms.js

      - name: Construir Tokens com Style Dictionary
        run: npx style-dictionary build --config config.json --verbose

      - name: Commitar Alterações
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
